version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.2.0
  helloworld: xavidop/circleci-orb-kc9@dev:alpha

executors:
  node:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run

filters: &filters
  tags:
    only: /.*/

jobs:
  greet-job:
    executor: node # use the `node` executor defined above
    steps:
      - helloworld/greet

workflows:
  publish-dev-orb:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - greet-job
      - helloworld/hello
      - orb-tools/lint
      - shellcheck/check:
          dir: ./src/scripts
      - orb-tools/pack
      - orb-tools/publish:
          context: dev
          requires: 
            - orb-tools/pack
          vcs_type: << pipeline.project.type >>
          orb_name: xavidop/circleci-orb-kc9
          pub_type: dev


  publish-orb:
    when: << pipeline.git.tag >>
    jobs:
      - orb-tools/lint:
          filters: *filters
      - shellcheck/check:
          filters: *filters
          dir: ./src/scripts
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          context: dev
          vcs_type: << pipeline.project.type >>
          orb_name: xavidop/circleci-orb-hello-world
          pub_type: production
          requires:
            - orb-tools/pack
            - orb-tools/lint
            - shellcheck/check
          filters: *filters